export interface EspecieData {
  id: string;
  nomePopular: string;
  nomeCientifico: string;
  grupo: "MAMIFERO" | "AVE" | "REPTIL" | "ANFIBIO" | "INVERTEBRADO" | "OUTRO";
  statusConservacao: "LC" | "NT" | "VU" | "EN" | "CR" | "DD";
  descricao: string;
  habitat: string;
  orientacoesConvivencia: string;
  fotoReferenciaUrl: string;
  ameacadaExtincao: boolean;
}

export const ESPECIES_REGIONAIS: EspecieData[] = [
  {
    id: "capivara",
    nomePopular: "Capivara",
    nomeCientifico: "Hydrochoerus hydrochaeris",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Maior roedor do mundo. Animal semi-aquático e herbívoro que vive em grupos familiares próximos a represas, lagoas e áreas gramadas de Araçoiaba da Serra.",
    habitat: "Margens de rios, represas, lagos municipais e várzeas.",
    orientacoesConvivencia: "Mantenha distância de segurança (ao menos 5 a 10 metros), especialmente se houver filhotes no bando. Não alimente e evite deitar em gramados frequentados por capivaras devido ao carrapato-estrela.",
    fotoReferenciaUrl: "/images/fauna/capivara.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "sarue",
    nomePopular: "Saruê / Gambá-de-orelha-branca",
    nomeCientifico: "Didelphis albiventris",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Marsupial nativo noturno e solitário. É um dos principais controladores naturais de pragas, alimentando-se ativamente de escorpiões, aranhas-armadeiras, carrapatos, baratas e pequenas serpentes.",
    habitat: "Matas, capões, forros de telhados e árvores em áreas urbanas e rurais.",
    orientacoesConvivencia: "Animal completamente inofensivo. Nunca agrida ou mate um saruê. Se entrar em sua casa ou forro, mantenha portas ou janelas abertas à noite para que ele saia sozinho em busca de alimento.",
    fotoReferenciaUrl: "/images/fauna/sarue.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "quati",
    nomePopular: "Quati",
    nomeCientifico: "Nasua nasua",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Mamífero onívoro de focinho alongado e cauda anelada. Vive em bandos ativos durante o dia revirando o solo e copas de árvores em busca de frutos e invertebrados.",
    habitat: "Florestas nativas, bordas de matas e parques ecológicos da região.",
    orientacoesConvivencia: "Não ofereça biscoitos, pães ou salgadinhos. Alimentos humanos provocam habituação e agressividade, além de doenças digestivas graves.",
    fotoReferenciaUrl: "/images/fauna/quati.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "tucano-toco",
    nomePopular: "Tucano-toco",
    nomeCientifico: "Ramphastos toco",
    grupo: "AVE",
    statusConservacao: "LC",
    descricao: "Maior espécie de tucano do planeta, emblemático pelo enorme bico amarelo-alaranjado com ponta preta. Desempenha papel ecológico vital na dispersão de sementes de árvores da Mata Atlântica e Cerrado.",
    habitat: "Copas de florestas, cerrados, pomares e áreas arborizadas da cidade.",
    orientacoesConvivencia: "Aprecie a observação à distância. Plante e preserve árvores frutíferas nativas (embaúba, pitangueira, figueira-brava) para atrair a espécie.",
    fotoReferenciaUrl: "/images/fauna/tucano-toco.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "sagui-tufo-preto",
    nomePopular: "Sagui-do-tufo-preto",
    nomeCientifico: "Callithrix penicillata",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Pequeno primata muito ágil com característicos tufos pretos circundando as orelhas. Alimenta-se de goma vegetal, seiva de árvores, pequenos frutos e insetos.",
    habitat: "Matas secundárias, capoeiras e áreas com árvores frutíferas.",
    orientacoesConvivencia: "Não alimente com restos de comida ou doces. A alimentação artificial desequilibra seu sistema biológico e favorece a transmissão de zoonoses.",
    fotoReferenciaUrl: "/images/fauna/sagui-tufo-preto.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "coruja-buraqueira",
    nomePopular: "Coruja-buraqueira",
    nomeCientifico: "Athene cunicularia",
    grupo: "AVE",
    statusConservacao: "LC",
    descricao: "Pequena coruja terrestre de olhos amarelos vivos e patas longas. Vive em buracos cavados no solo e atua com grande eficiência no controle de roedores e gafanhotos.",
    habitat: "Campos abertos, pastos, terrenos baldios, canteiros centrais e margens de estradas.",
    orientacoesConvivencia: "Não mexa nem tente fechar as tocas no chão. Ao avistar ninhos em pastos ou calçadas, mantenha cães e animais domésticos afastados.",
    fotoReferenciaUrl: "/images/fauna/coruja-buraqueira.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "teiu",
    nomePopular: "Teiú",
    nomeCientifico: "Salvator merianae",
    grupo: "REPTIL",
    statusConservacao: "LC",
    descricao: "Maior lagarto da fauna brasileira, podendo atingir até 1,40m de comprimento. Possui escamas escuras com faixas claras e hábito de tomar sol sobre pedras e troncos caídos.",
    habitat: "Bordas de matas, capoeiras, pomares e áreas rurais.",
    orientacoesConvivencia: "Animal dócil que prefere fugir ao notar presença humana. Não encurrale nem tente manuseá-lo, pois pode se defender com chicotadas de cauda e mordidas se acuado.",
    fotoReferenciaUrl: "/images/fauna/teiu.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "tamandua-bandeira",
    nomePopular: "Tamanduá-bandeira",
    nomeCientifico: "Myrmecophaga tridactyla",
    grupo: "MAMIFERO",
    statusConservacao: "VU",
    descricao: "Espécie ameaçada de extinção (Vulnerável). Mamífero fascinante desprovido de dentes com focinho tubular e cauda plumosa em formato de bandeira. Consome milhares de formigas e cupins diariamente.",
    habitat: "Campos, cerrados e fragmentos florestais protegidos como a Flona de Ipanema.",
    orientacoesConvivencia: "Espécie ameaçada estritamente protegida por lei. Se avistar em rodovias ou perto de residências, avise de imediato a Defesa Civil ou Polícia Ambiental.",
    fotoReferenciaUrl: "/images/fauna/tamandua-bandeira.jpg",
    ameacadaExtincao: true,
  },
  {
    id: "onca-parda",
    nomePopular: "Onça-parda / Suçuarana",
    nomeCientifico: "Puma concolor",
    grupo: "MAMIFERO",
    statusConservacao: "VU",
    descricao: "Segundo maior felino do continente americano. Animal de pelagem avermelhada e corpo esguio, topo de cadeia alimentar e regulador do ecossistema das serras e matas da região.",
    habitat: "Matas densas, encostas de morros e áreas de preservação florestal.",
    orientacoesConvivencia: "Encontros são extremamente raros. Se avistar, não corra, não vire as costas, mantenha contato visual e recolha crianças. Comunique imediatamente as autoridades ambientais.",
    fotoReferenciaUrl: "/images/fauna/onca-parda.jpg",
    ameacadaExtincao: true,
  },
  {
    id: "carcara",
    nomePopular: "Carcará",
    nomeCientifico: "Caracara plancus",
    grupo: "AVE",
    statusConservacao: "LC",
    descricao: "Ave de rapina de porte médio com penacho preto na cabeça e bico forte e curvo. Onívora e oportunista, desempenha função sanitária ao consumir carcaças e pequenos animais atropelados.",
    habitat: "Campos, pastagens, bordas de matas e margens de rodovias e vicinais.",
    orientacoesConvivencia: "Ave de rapina benéfica para a limpeza ambiental. Não interfira quando estiver forrageando às margens das estradas.",
    fotoReferenciaUrl: "/images/fauna/carcara.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "lobo-guara",
    nomePopular: "Lobo-guará",
    nomeCientifico: "Chrysocyon brachyurus",
    grupo: "MAMIFERO",
    statusConservacao: "VU",
    descricao: "Maior canídeo silvestre da América do Sul, caracterizado pelas pernas longas e pelagem avermelhada. Possui hábitos crepusculares e solitários, sendo fundamental na dispersão de frutos do cerrado.",
    habitat: "Campos abertos, bordas de cerradão e remanescentes florestais no entorno do Morro do Araçoiaba.",
    orientacoesConvivencia: "Animal tímido e inofensivo ao ser humano. Mantenha distância respeitosa, reduza a velocidade em estradas rurais e jamais deixe alimentos expostos.",
    fotoReferenciaUrl: "/images/fauna/lobo-guara.jpg",
    ameacadaExtincao: true,
  },
  {
    id: "jaguatirica",
    nomePopular: "Jaguatirica",
    nomeCientifico: "Leopardus pardalis",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Felino de porte médio com pelagem amarelada marcada por ocelos escuros alongados. Ágil escaladora e excelente nadadora, tem hábitos predominantemente noturnos e carnívoros.",
    habitat: "Fragmentos densos de Mata Atlântica e matas ciliares conectadas à Floresta Nacional de Ipanema.",
    orientacoesConvivencia: "Não tente aproximação nem encurrale. Mantenha animais domésticos abrigados durante a noite e informe avistamentos à equipe ambiental.",
    fotoReferenciaUrl: "/images/fauna/jaguatirica.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "tamandua-mirim",
    nomePopular: "Tamanduá-mirim",
    nomeCientifico: "Tamandua tetradactyla",
    grupo: "MAMIFERO",
    statusConservacao: "LC",
    descricao: "Conhecido pela pelagem dourada com mancha escura em formato de colete e cauda preênsil. Especialista em consumir cupins e formigas arbóreas, controlando populações de insetos.",
    habitat: "Matas secundárias, capoeiras e pomares rurais arborizados no município.",
    orientacoesConvivencia: "Possui garras curvas poderosas para defesa. Mantenha cães afastados para evitar ferimentos mútuos e deixe o animal seguir seu curso na vegetação.",
    fotoReferenciaUrl: "/images/fauna/tamandua-mirim.jpg",
    ameacadaExtincao: false,
  },
  {
    id: "urubu-rei",
    nomePopular: "Urubu-rei",
    nomeCientifico: "Sarcoramphus papa",
    grupo: "AVE",
    statusConservacao: "LC",
    descricao: "Ave de grande porte com envergadura de até 2 metros, cabeça nua com cores vibrantes e plumagem branca e preta. Realiza serviço ecossistêmico crucial ao decompor carcaças.",
    habitat: "Florestas preservadas e paredões rochosos da serra com correntes de ar ascendentes.",
    orientacoesConvivencia: "Espécie silvestre protegida. Evite perturbar locais de pouso ou ninhais nas encostas rochosas.",
    fotoReferenciaUrl: "/images/fauna/urubu-rei.jpg",
    ameacadaExtincao: false,
  },
];
